// config.js - Centralized configuration and constants

export const DOM_IDS = {
    // Input controls
    inputMethod: 'inputMethod',
    sourceSystem: 'sourceSystem',
    comparisonSystem: 'comparisonSystem',
    progressIndex: 'progressIndex',
    customKanji: 'customKanji',

    // Containers
    indexInput: 'indexInput',
    customInput: 'customInput',
    controlsPanel: 'controlsPanel',
    statsSection: 'statsSection',
    searchSection: 'searchSection',
    errorSection: 'errorSection',

    // Dropdowns
    sourceLevelToggle: 'sourceLevelToggle',
    sourceLevelMenu: 'sourceLevelMenu',
    sourceLevelText: 'sourceLevelText',
    comparisonLevelToggle: 'comparisonLevelToggle',
    comparisonLevelMenu: 'comparisonLevelMenu',
    comparisonLevelText: 'comparisonLevelText',

    // Display areas
    kanjiGrid: 'kanjiGrid',
    stats: 'stats',
    kanjiInfoPanel: 'kanjiInfoPanel',
    kanjiInfoContent: 'kanjiInfoContent',
    jukugoPanel: 'jukugoPanel',
    jukugoPanelContent: 'jukugoPanelContent',

    // Buttons and inputs
    visualizeBtn: 'visualizeBtn',
    kanjiSearchInput: 'kanjiSearchInput',
    onyomiCheckbox: 'onyomi-checkbox',
    kunyomiCheckbox: 'kunyomi-checkbox'
};

export const KANJI_SYSTEMS = {
    japanese_school_grades: [
        { file: 'japanese_school_grades_elementary_1.txt', label: 'Elementary 1 (80 kanji)' },
        { file: 'japanese_school_grades_elementary_2.txt', label: 'Elementary 2 (160 kanji)' },
        { file: 'japanese_school_grades_elementary_3.txt', label: 'Elementary 3 (200 kanji)' },
        { file: 'japanese_school_grades_elementary_4.txt', label: 'Elementary 4 (200 kanji)' },
        { file: 'japanese_school_grades_elementary_5.txt', label: 'Elementary 5 (185 kanji)' },
        { file: 'japanese_school_grades_elementary_6.txt', label: 'Elementary 6 (181 kanji)' },
        { file: 'japanese_school_grades_secondary_1.txt', label: 'Secondary 1 (316 kanji)' },
        { file: 'japanese_school_grades_secondary_2.txt', label: 'Secondary 2 (285 kanji)' },
        { file: 'japanese_school_grades_secondary_3.txt', label: 'Secondary 3 (333 kanji)' },
        { file: 'japanese_school_grades_advanced.txt', label: 'Advanced (196 kanji)' },
        // { file: 'japanese_school_grades_other.txt', label: 'Other (4900 kanji)' },
    ],
    jlpt_levels: [
        { file: 'jlpt_beginner.txt', label: 'Beginner (80 kanji)' },
        { file: 'jlpt_basic.txt', label: 'Basic (166 kanji)' },
        { file: 'jlpt_intermediate.txt', label: 'Intermediate (370 kanji)' },
        { file: 'jlpt_advanced.txt', label: 'Advanced (370 kanji)' },
        { file: 'jlpt_expert.txt', label: 'Expert (1240 kanji)' },
        // { file: 'jlpt_other.txt', label: 'Other (4810 kanji)' },
    ],
    kanji_learners_course: [
        { file: 'klc_level_1.txt', label: 'Level 1 (100 kanji)' },
        { file: 'klc_level_2.txt', label: 'Level 2 (100 kanji)' },
        { file: 'klc_level_3.txt', label: 'Level 3 (100 kanji)' },
        { file: 'klc_level_4.txt', label: 'Level 4 (100 kanji)' },
        { file: 'klc_level_5.txt', label: 'Level 5 (100 kanji)' },
        { file: 'klc_level_6.txt', label: 'Level 6 (100 kanji)' },
        { file: 'klc_level_7.txt', label: 'Level 7 (100 kanji)' },
        { file: 'klc_level_8.txt', label: 'Level 8 (100 kanji)' },
        { file: 'klc_level_9.txt', label: 'Level 9 (100 kanji)' },
        { file: 'klc_level_10.txt', label: 'Level 10 (100 kanji)' },
        { file: 'klc_level_11.txt', label: 'Level 11 (100 kanji)' },
        { file: 'klc_level_12.txt', label: 'Level 12 (100 kanji)' },
        { file: 'klc_level_13.txt', label: 'Level 13 (100 kanji)' },
        { file: 'klc_level_14.txt', label: 'Level 14 (100 kanji)' },
        { file: 'klc_level_15.txt', label: 'Level 15 (100 kanji)' },
        { file: 'klc_level_16.txt', label: 'Level 16 (100 kanji)' },
        { file: 'klc_level_17.txt', label: 'Level 17 (100 kanji)' },
        { file: 'klc_level_18.txt', label: 'Level 18 (100 kanji)' },
        { file: 'klc_level_19.txt', label: 'Level 19 (100 kanji)' },
        { file: 'klc_level_20.txt', label: 'Level 20 (100 kanji)' },
        { file: 'klc_level_21.txt', label: 'Level 21 (100 kanji)' },
        { file: 'klc_level_22.txt', label: 'Level 22 (100 kanji)' },
        { file: 'klc_level_23.txt', label: 'Level 23 (100 kanji)' },
        // { file: 'klc_other.txt', label: 'Other (4736 kanji)' },
    ],
    jouyou_2020: [
        { file: 'jouyou_elementary_1.txt', label: 'Elementary 1 (80 kanji)' },
        { file: 'jouyou_elementary_2.txt', label: 'Elementary 2 (160 kanji)' },
        { file: 'jouyou_elementary_3.txt', label: 'Elementary 3 (200 kanji)' },
        { file: 'jouyou_elementary_4.txt', label: 'Elementary 4 (202 kanji)' },
        { file: 'jouyou_elementary_5.txt', label: 'Elementary 5 (193 kanji)' },
        { file: 'jouyou_elementary_6.txt', label: 'Elementary 6 (191 kanji)' },
        { file: 'jouyou_secondary_1.txt', label: 'Secondary 1 (313 kanji)' },
        { file: 'jouyou_secondary_2.txt', label: 'Secondary 2 (284 kanji)' },
        { file: 'jouyou_secondary_3.txt', label: 'Secondary 3 (328 kanji)' },
        { file: 'jouyou_advanced.txt', label: 'Advanced (185 kanji)' },
        // { file: 'jouyou_other.txt', label: 'Other (4900 kanji)' },
    ],
    jlpt_revised: [
        { file: 'jlpt_rev_beginner.txt', label: 'Beginner (103 kanji)' },
        { file: 'jlpt_rev_basic.txt', label: 'Basic (181 kanji)' },
        { file: 'jlpt_rev_intermediate.txt', label: 'Intermediate (324 kanji)' },
        { file: 'jlpt_rev_advanced.txt', label: 'Advanced (415 kanji)' },
        { file: 'jlpt_rev_expert.txt', label: 'Expert (1207 kanji)' },
        // { file: 'jlpt_rev_other.txt', label: 'Other (4806 kanji)' },
    ],
    frequency_media: [
        { file: 'freq_stage_1.txt', label: 'Stage 1 (100 kanji)' },
        { file: 'freq_stage_2.txt', label: 'Stage 2 (100 kanji)' },
        { file: 'freq_stage_3.txt', label: 'Stage 3 (100 kanji)' },
        { file: 'freq_stage_4.txt', label: 'Stage 4 (100 kanji)' },
        { file: 'freq_stage_5.txt', label: 'Stage 5 (100 kanji)' },
        { file: 'freq_stage_6.txt', label: 'Stage 6 (100 kanji)' },
        { file: 'freq_stage_7.txt', label: 'Stage 7 (100 kanji)' },
        { file: 'freq_stage_8.txt', label: 'Stage 8 (100 kanji)' },
        { file: 'freq_stage_9.txt', label: 'Stage 9 (100 kanji)' },
        { file: 'freq_stage_10.txt', label: 'Stage 10 (100 kanji)' },
        { file: 'freq_stage_11.txt', label: 'Stage 11 (100 kanji)' },
        { file: 'freq_stage_12.txt', label: 'Stage 12 (100 kanji)' },
        { file: 'freq_stage_13.txt', label: 'Stage 13 (100 kanji)' },
        { file: 'freq_stage_14.txt', label: 'Stage 14 (100 kanji)' },
        { file: 'freq_stage_15.txt', label: 'Stage 15 (100 kanji)' },
        { file: 'freq_stage_16.txt', label: 'Stage 16 (100 kanji)' },
        { file: 'freq_stage_17.txt', label: 'Stage 17 (100 kanji)' },
        { file: 'freq_stage_18.txt', label: 'Stage 18 (100 kanji)' },
        { file: 'freq_stage_19.txt', label: 'Stage 19 (100 kanji)' },
        { file: 'freq_stage_20.txt', label: 'Stage 20 (100 kanji)' },
        // { file: 'freq_other.txt', label: 'Other (5036 kanji)' },
    ],
    kanji_kentei: [
        { file: 'kk_level_10.txt', label: 'Level 10 (80 kanji)' },
        { file: 'kk_level_9.txt', label: 'Level 9 (160 kanji)' },
        { file: 'kk_level_8.txt', label: 'Level 8 (200 kanji)' },
        { file: 'kk_level_7.txt', label: 'Level 7 (200 kanji)' },
        { file: 'kk_level_6.txt', label: 'Level 6 (185 kanji)' },
        { file: 'kk_level_5.txt', label: 'Level 5 (181 kanji)' },
        { file: 'kk_level_4.txt', label: 'Level 4 (316 kanji)' },
        { file: 'kk_level_3.txt', label: 'Level 3 (285 kanji)' },
        { file: 'kk_level_pre_2.txt', label: 'Level Pre-2 (333 kanji)' },
        { file: 'kk_level_2.txt', label: 'Level 2 (196 kanji)' },
        { file: 'kk_level_pre_1.txt', label: 'Level Pre-1 (891 kanji)' },
        { file: 'kk_level_1.txt', label: 'Level 1 (3328 kanji)' },
        // { file: 'kk_other.txt', label: 'Other (681 kanji)' },
    ],
    kanji_kentei_2020: [
        { file: 'kk_level_10.txt', label: 'Level 10 (80 kanji)' },
        { file: 'kk_level_9.txt', label: 'Level 9 (160 kanji)' },
        { file: 'kk_level_8.txt', label: 'Level 8 (200 kanji)' },
        { file: 'kk_level_7.txt', label: 'Level 7 (202 kanji)' },
        { file: 'kk_level_6.txt', label: 'Level 6 (193 kanji)' },
        { file: 'kk_level_5.txt', label: 'Level 5 (191 kanji)' },
        { file: 'kk_level_4.txt', label: 'Level 4 (313 kanji)' },
        { file: 'kk_level_3.txt', label: 'Level 3 (284 kanji)' },
        { file: 'kk_level_pre_2.txt', label: 'Level Pre-2 (328 kanji)' },
        { file: 'kk_level_2.txt', label: 'Level 2 (185 kanji)' },
        { file: 'kk_level_pre_1.txt', label: 'Level Pre-1 (891 kanji)' },
        { file: 'kk_level_1.txt', label: 'Level 1 (3328 kanji)' },
        // { file: 'kk_other.txt', label: 'Other (681 kanji)' },
    ],
    rtk_6th: [
        { file: 'rtk_6th_lesson_1.txt', label: 'Lesson 1 (15 kanji)' },
        { file: 'rtk_6th_lesson_2.txt', label: 'Lesson 2 (19 kanji)' },
        { file: 'rtk_6th_lesson_3.txt', label: 'Lesson 3 (20 kanji)' },
        { file: 'rtk_6th_lesson_4.txt', label: 'Lesson 4 (20 kanji)' },
        { file: 'rtk_6th_lesson_5.txt', label: 'Lesson 5 (24 kanji)' },
        { file: 'rtk_6th_lesson_6.txt', label: 'Lesson 6 (11 kanji)' },
        { file: 'rtk_6th_lesson_7.txt', label: 'Lesson 7 (24 kanji)' },
        { file: 'rtk_6th_lesson_8.txt', label: 'Lesson 8 (51 kanji)' },
        { file: 'rtk_6th_lesson_9.txt', label: 'Lesson 9 (22 kanji)' },
        { file: 'rtk_6th_lesson_10.txt', label: 'Lesson 10 (43 kanji)' },
        { file: 'rtk_6th_lesson_11.txt', label: 'Lesson 11 (15 kanji)' },
        { file: 'rtk_6th_lesson_12.txt', label: 'Lesson 12 (30 kanji)' },
        { file: 'rtk_6th_lesson_13.txt', label: 'Lesson 13 (26 kanji)' },
        { file: 'rtk_6th_lesson_14.txt', label: 'Lesson 14 (25 kanji)' },
        { file: 'rtk_6th_lesson_15.txt', label: 'Lesson 15 (31 kanji)' },
        { file: 'rtk_6th_lesson_16.txt', label: 'Lesson 16 (19 kanji)' },
        { file: 'rtk_6th_lesson_17.txt', label: 'Lesson 17 (27 kanji)' },
        { file: 'rtk_6th_lesson_18.txt', label: 'Lesson 18 (92 kanji)' },
        { file: 'rtk_6th_lesson_19.txt', label: 'Lesson 19 (33 kanji)' },
        { file: 'rtk_6th_lesson_20.txt', label: 'Lesson 20 (6 kanji)' },
        { file: 'rtk_6th_lesson_21.txt', label: 'Lesson 21 (66 kanji)' },
        { file: 'rtk_6th_lesson_22.txt', label: 'Lesson 22 (67 kanji)' },
        { file: 'rtk_6th_lesson_23.txt', label: 'Lesson 23 (142 kanji)' },
        { file: 'rtk_6th_lesson_24.txt', label: 'Lesson 24 (30 kanji)' },
        { file: 'rtk_6th_lesson_25.txt', label: 'Lesson 25 (99 kanji)' },
        { file: 'rtk_6th_lesson_26.txt', label: 'Lesson 26 (65 kanji)' },
        { file: 'rtk_6th_lesson_27.txt', label: 'Lesson 27 (81 kanji)' },
        { file: 'rtk_6th_lesson_28.txt', label: 'Lesson 28 (20 kanji)' },
        { file: 'rtk_6th_lesson_29.txt', label: 'Lesson 29 (43 kanji)' },
        { file: 'rtk_6th_lesson_30.txt', label: 'Lesson 30 (39 kanji)' },
        { file: 'rtk_6th_lesson_31.txt', label: 'Lesson 31 (62 kanji)' },
        { file: 'rtk_6th_lesson_32.txt', label: 'Lesson 32 (37 kanji)' },
        { file: 'rtk_6th_lesson_33.txt', label: 'Lesson 33 (32 kanji)' },
        { file: 'rtk_6th_lesson_34.txt', label: 'Lesson 34 (53 kanji)' },
        { file: 'rtk_6th_lesson_35.txt', label: 'Lesson 35 (41 kanji)' },
        { file: 'rtk_6th_lesson_36.txt', label: 'Lesson 36 (66 kanji)' },
        { file: 'rtk_6th_lesson_37.txt', label: 'Lesson 37 (37 kanji)' },
        { file: 'rtk_6th_lesson_38.txt', label: 'Lesson 38 (62 kanji)' },
        { file: 'rtk_6th_lesson_39.txt', label: 'Lesson 39 (55 kanji)' },
        { file: 'rtk_6th_lesson_40.txt', label: 'Lesson 40 (60 kanji)' },
        { file: 'rtk_6th_lesson_41.txt', label: 'Lesson 41 (32 kanji)' },
        { file: 'rtk_6th_lesson_42.txt', label: 'Lesson 42 (34 kanji)' },
        { file: 'rtk_6th_lesson_43.txt', label: 'Lesson 43 (36 kanji)' },
        { file: 'rtk_6th_lesson_44.txt', label: 'Lesson 44 (33 kanji)' },
        { file: 'rtk_6th_lesson_45.txt', label: 'Lesson 45 (48 kanji)' },
        { file: 'rtk_6th_lesson_46.txt', label: 'Lesson 46 (20 kanji)' },
        { file: 'rtk_6th_lesson_47.txt', label: 'Lesson 47 (32 kanji)' },
        { file: 'rtk_6th_lesson_48.txt', label: 'Lesson 48 (24 kanji)' },
        { file: 'rtk_6th_lesson_49.txt', label: 'Lesson 49 (27 kanji)' },
        { file: 'rtk_6th_lesson_50.txt', label: 'Lesson 50 (28 kanji)' },
        { file: 'rtk_6th_lesson_51.txt', label: 'Lesson 51 (28 kanji)' },
        { file: 'rtk_6th_lesson_52.txt', label: 'Lesson 52 (24 kanji)' },
        { file: 'rtk_6th_lesson_53.txt', label: 'Lesson 53 (55 kanji)' },
        { file: 'rtk_6th_lesson_54.txt', label: 'Lesson 54 (30 kanji)' },
        { file: 'rtk_6th_lesson_55.txt', label: 'Lesson 55 (20 kanji)' },
        { file: 'rtk_6th_lesson_56.txt', label: 'Lesson 56 (19 kanji)' },
        // { file: 'rtk_6th_other.txt', label: 'Other (4836 kanji)' },
    ],
    kanji_in_context: [
        { file: 'kic_level_1.txt', label: 'Level 1 (250 kanji)' },
        { file: 'kic_level_2.txt', label: 'Level 2 (100 kanji)' },
        { file: 'kic_level_3.txt', label: 'Level 3 (850 kanji)' },
        { file: 'kic_level_4.txt', label: 'Level 4 (220 kanji)' },
        { file: 'kic_level_5.txt', label: 'Level 5 (412 kanji)' },
        { file: 'kic_level_6.txt', label: 'Level 6 (110 kanji)' },
        { file: 'kic_level_7.txt', label: 'Level 7 (194 kanji)' },
        // { file: 'kic_other.txt', label: 'Other (4900 kanji)' },
    ],
    hadamitzky_spahn: [
        { file: 'hs_level_1.txt', label: 'Level 1 (50 kanji)' },
        { file: 'hs_level_2.txt', label: 'Level 2 (50 kanji)' },
        { file: 'hs_level_3.txt', label: 'Level 3 (50 kanji)' },
        { file: 'hs_level_4.txt', label: 'Level 4 (50 kanji)' },
        { file: 'hs_level_5.txt', label: 'Level 5 (50 kanji)' },
        { file: 'hs_level_6.txt', label: 'Level 6 (50 kanji)' },
        { file: 'hs_level_7.txt', label: 'Level 7 (50 kanji)' },
        { file: 'hs_level_8.txt', label: 'Level 8 (50 kanji)' },
        { file: 'hs_level_9.txt', label: 'Level 9 (50 kanji)' },
        { file: 'hs_level_10.txt', label: 'Level 10 (50 kanji)' },
        { file: 'hs_level_11.txt', label: 'Level 11 (50 kanji)' },
        { file: 'hs_level_12.txt', label: 'Level 12 (50 kanji)' },
        { file: 'hs_level_13.txt', label: 'Level 13 (50 kanji)' },
        { file: 'hs_level_14.txt', label: 'Level 14 (50 kanji)' },
        { file: 'hs_level_15.txt', label: 'Level 15 (50 kanji)' },
        { file: 'hs_level_16.txt', label: 'Level 16 (50 kanji)' },
        { file: 'hs_level_17.txt', label: 'Level 17 (50 kanji)' },
        { file: 'hs_level_18.txt', label: 'Level 18 (50 kanji)' },
        { file: 'hs_level_19.txt', label: 'Level 19 (50 kanji)' },
        { file: 'hs_level_20.txt', label: 'Level 20 (50 kanji)' },
        { file: 'hs_level_21.txt', label: 'Level 21 (50 kanji)' },
        { file: 'hs_level_22.txt', label: 'Level 22 (50 kanji)' },
        { file: 'hs_level_23.txt', label: 'Level 23 (50 kanji)' },
        { file: 'hs_level_24.txt', label: 'Level 24 (50 kanji)' },
        { file: 'hs_level_25.txt', label: 'Level 25 (50 kanji)' },
        { file: 'hs_level_26.txt', label: 'Level 26 (50 kanji)' },
        { file: 'hs_level_27.txt', label: 'Level 27 (49 kanji)' },
        { file: 'hs_level_28.txt', label: 'Level 28 (50 kanji)' },
        { file: 'hs_level_29.txt', label: 'Level 29 (50 kanji)' },
        { file: 'hs_level_30.txt', label: 'Level 30 (50 kanji)' },
        { file: 'hs_level_31.txt', label: 'Level 31 (50 kanji)' },
        { file: 'hs_level_32.txt', label: 'Level 32 (50 kanji)' },
        { file: 'hs_level_33.txt', label: 'Level 33 (50 kanji)' },
        { file: 'hs_level_34.txt', label: 'Level 34 (50 kanji)' },
        { file: 'hs_level_35.txt', label: 'Level 35 (50 kanji)' },
        { file: 'hs_level_36.txt', label: 'Level 36 (50 kanji)' },
        { file: 'hs_level_37.txt', label: 'Level 37 (50 kanji)' },
        { file: 'hs_level_38.txt', label: 'Level 38 (50 kanji)' },
        { file: 'hs_level_39.txt', label: 'Level 39 (50 kanji)' },
        { file: 'hs_level_40.txt', label: 'Level 40 (50 kanji)' },
        { file: 'hs_level_41.txt', label: 'Level 41 (50 kanji)' },
        { file: 'hs_level_42.txt', label: 'Level 42 (50 kanji)' },
        { file: 'hs_level_43.txt', label: 'Level 43 (41 kanji)' },
        // { file: 'hs_other.txt', label: 'Other (4896 kanji)' },
    ],
    wanikani: [
        { file: 'wanikani_level_1.txt', label: 'Level 1 (18 kanji)' },
        { file: 'wanikani_level_2.txt', label: 'Level 2 (34 kanji)' },
        { file: 'wanikani_level_3.txt', label: 'Level 3 (31 kanji)' },
        { file: 'wanikani_level_4.txt', label: 'Level 4 (39 kanji)' },
        { file: 'wanikani_level_5.txt', label: 'Level 5 (46 kanji)' },
        { file: 'wanikani_level_6.txt', label: 'Level 6 (36 kanji)' },
        { file: 'wanikani_level_7.txt', label: 'Level 7 (37 kanji)' },
        { file: 'wanikani_level_8.txt', label: 'Level 8 (34 kanji)' },
        { file: 'wanikani_level_9.txt', label: 'Level 9 (40 kanji)' },
        { file: 'wanikani_level_10.txt', label: 'Level 10 (42 kanji)' },
        { file: 'wanikani_level_11.txt', label: 'Level 11 (39 kanji)' },
        { file: 'wanikani_level_12.txt', label: 'Level 12 (40 kanji)' },
        { file: 'wanikani_level_13.txt', label: 'Level 13 (35 kanji)' },
        { file: 'wanikani_level_14.txt', label: 'Level 14 (33 kanji)' },
        { file: 'wanikani_level_15.txt', label: 'Level 15 (38 kanji)' },
        { file: 'wanikani_level_16.txt', label: 'Level 16 (33 kanji)' },
        { file: 'wanikani_level_17.txt', label: 'Level 17 (35 kanji)' },
        { file: 'wanikani_level_18.txt', label: 'Level 18 (31 kanji)' },
        { file: 'wanikani_level_19.txt', label: 'Level 19 (34 kanji)' },
        { file: 'wanikani_level_20.txt', label: 'Level 20 (32 kanji)' },
        { file: 'wanikani_level_21.txt', label: 'Level 21 (33 kanji)' },
        { file: 'wanikani_level_22.txt', label: 'Level 22 (38 kanji)' },
        { file: 'wanikani_level_23.txt', label: 'Level 23 (34 kanji)' },
        { file: 'wanikani_level_24.txt', label: 'Level 24 (32 kanji)' },
        { file: 'wanikani_level_25.txt', label: 'Level 25 (39 kanji)' },
        { file: 'wanikani_level_26.txt', label: 'Level 26 (33 kanji)' },
        { file: 'wanikani_level_27.txt', label: 'Level 27 (32 kanji)' },
        { file: 'wanikani_level_28.txt', label: 'Level 28 (35 kanji)' },
        { file: 'wanikani_level_29.txt', label: 'Level 29 (35 kanji)' },
        { file: 'wanikani_level_30.txt', label: 'Level 30 (33 kanji)' },
        { file: 'wanikani_level_31.txt', label: 'Level 31 (37 kanji)' },
        { file: 'wanikani_level_32.txt', label: 'Level 32 (34 kanji)' },
        { file: 'wanikani_level_33.txt', label: 'Level 33 (32 kanji)' },
        { file: 'wanikani_level_34.txt', label: 'Level 34 (33 kanji)' },
        { file: 'wanikani_level_35.txt', label: 'Level 35 (35 kanji)' },
        { file: 'wanikani_level_36.txt', label: 'Level 36 (38 kanji)' },
        { file: 'wanikani_level_37.txt', label: 'Level 37 (35 kanji)' },
        { file: 'wanikani_level_38.txt', label: 'Level 38 (35 kanji)' },
        { file: 'wanikani_level_39.txt', label: 'Level 39 (35 kanji)' },
        { file: 'wanikani_level_40.txt', label: 'Level 40 (36 kanji)' },
        { file: 'wanikani_level_41.txt', label: 'Level 41 (33 kanji)' },
        { file: 'wanikani_level_42.txt', label: 'Level 42 (34 kanji)' },
        { file: 'wanikani_level_43.txt', label: 'Level 43 (33 kanji)' },
        { file: 'wanikani_level_44.txt', label: 'Level 44 (31 kanji)' },
        { file: 'wanikani_level_45.txt', label: 'Level 45 (34 kanji)' },
        { file: 'wanikani_level_46.txt', label: 'Level 46 (36 kanji)' },
        { file: 'wanikani_level_47.txt', label: 'Level 47 (37 kanji)' },
        { file: 'wanikani_level_48.txt', label: 'Level 48 (37 kanji)' },
        { file: 'wanikani_level_49.txt', label: 'Level 49 (35 kanji)' },
        { file: 'wanikani_level_50.txt', label: 'Level 50 (34 kanji)' },
        { file: 'wanikani_level_51.txt', label: 'Level 51 (34 kanji)' },
        { file: 'wanikani_level_52.txt', label: 'Level 52 (36 kanji)' },
        { file: 'wanikani_level_53.txt', label: 'Level 53 (34 kanji)' },
        { file: 'wanikani_level_54.txt', label: 'Level 54 (35 kanji)' },
        { file: 'wanikani_level_55.txt', label: 'Level 55 (36 kanji)' },
        { file: 'wanikani_level_56.txt', label: 'Level 56 (35 kanji)' },
        { file: 'wanikani_level_57.txt', label: 'Level 57 (32 kanji)' },
        { file: 'wanikani_level_58.txt', label: 'Level 58 (33 kanji)' },
        { file: 'wanikani_level_59.txt', label: 'Level 59 (34 kanji)' },
        { file: 'wanikani_level_60.txt', label: 'Level 60 (32 kanji)' },
    ],
};




export const KANJI_SYSTEM_ABBR = {
    kanji_kentei_2020: 'KK (2020)',
    japanese_school_grades: 'jōyō',
    jlpt_levels: 'JLPT',
    kanji_learners_course: 'KLC',
    jlpt_revised: 'JLPT (rev)',
    jouyou_2020: 'jōyō (2020)',
    frequency_media: 'freq. in media',
    kanji_kentei: 'KK',
    rtk_1st: 'RTK (1st)',
    rtk_6th: 'RTK (6th)',
    kanji_in_context: 'KIC',
    hadamitzky_spahn: 'H/S',
    wanikani: 'Wanikani'
};


export const CATEGORY_MAPPING = {
    "Japanese School Grades": "japanese_school_grades",
    "JLPT levels": "jlpt_levels",
    "Kanji Learner's Course": "kanji_learners_course",
    "Jouyou (2020 revision)": "jouyou_2020",
    "JLPT levels (revised)": "jlpt_revised",
    "Frequency in media": "frequency_media",
    "Kanji Kentei": "kanji_kentei",
    "Kanji Kentei (2020 revision)": "kanji_kentei_2020",
    "Remembering the Kanji - 1st Edition": "rtk_1st",
    "Remembering the Kanji - 6th Edition": "rtk_6th",
    "Kanji in Context": "kanji_in_context",
    "Hadamitzky/Spahn": "hadamitzky_spahn",
    "Wanikani": "wanikani"
}


export const KANJI_TYPES = {
    LEARNED: 'learned',
    UNLEARNED: 'unlearned',
    USER_ONLY: 'user-only'
};

export const INPUT_METHODS = {
    INDEX: 'index',
    CUSTOM: 'custom'
};

export const CSS_CLASSES = {
    checkboxItem: 'checkbox-item',
    checkboxItemAll: 'checkbox-item all',
    dropdownShow: 'show',
    loading: 'loading'
};